# Dockerfile.tensorflow
FROM tensorflow/tensorflow:2.19.0-gpu-jupyter

RUN apt-get update && apt-get install -y git curl

RUN pip install matplotlib pandas scikit-learn

EXPOSE 8888

# Dockerfile.pytorch
FROM nvidia/cuda:12.5.1-cudnn-devel-ubuntu22.04

RUN apt-get update && apt-get install -y \
    python3 python3-pip git curl && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    pip install --upgrade pip

RUN pip install torch==2.6.0 torchvision==0.21.0 torchaudio==2.6.0 --index-url https://download.pytorch.org/whl/cu126

RUN pip install notebook jupyterlab matplotlib pandas scikit-learn

EXPOSE 8888

CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--no-browser", "--allow-root", "--NotebookApp.token=''", "--NotebookApp.password=''"]

# TensorFlow
docker build -t my-tf:2.19 -f Dockerfile.tensorflow .

# PyTorch
docker build -t my-torch:2.6 -f Dockerfile.pytorch .
